### ISSUE TITLE
Repository descriptions

### ISSUE THREAD

**Issue by tomaj** [pryznar/smsconnect-ruby#5]
There is wrong project description
```Send and receive SMS with node.js (for Czech Republic)```

it should be 
```Send and receive SMS with Ruby (for Czech Republic)```

**Comment by pryznar** [comment]
thanx, fixed

**Comment by tomaj** [comment]
Sorry by I meant this: https://www.dropbox.com/s/9zm7sd2jj4d49mo/Screenshot%202017-04-25%2011.34.39.png?dl=0 - (project description on github) :-)

**Comment by pryznar** [comment]
Fixed :)
